name: Build, package and release clang+llvm
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: write

jobs:
  build:
    strategy:
      matrix:
        arch: [arm64, x86-64]
        include:
          - arch: arm64
            os: macos-14
          - arch: x86-64
            os: macos-13
      fail-fast: true
      max-parallel: 2
    uses: ./.github/workflows/jobs.yml
    with:
      arch: ${{ matrix.arch }}
      os:  ${{ matrix.os }}
